---
title: "BBWM initial recovery"
author: "Kaizad Patel"
output: github_document
---

`r Sys.Date()`

```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo=FALSE,message=FALSE,warning=FALSE,
                      collapse = TRUE,
                      comment = "#>",
                      fig.path = "images/"
                      )

source("0-bbwm_packages.R")

all = read.csv("processed/concentrations.csv")
annual = read.csv("processed/fluxes.csv")
summary = read.csv("processed/summary.csv")

```


## nitrate

```{r nitrate}
#nitrate
ggplot (na.omit(annual), 
                     aes(x = WY, y = NO3_vol,color = Watershed,fill=Watershed,shape = Watershed,linetype=Watershed))+
  geom_point(data=all,
             aes(x = WY, y = NO3, color = "grey"))+
  geom_smooth(alpha = 0.2)+
  geom_point(size=3,stroke=1.5)+
  scale_color_got(discrete=TRUE,option = "tully")+
  scale_fill_got(discrete=TRUE,option = "tully")+
  scale_shape_manual(values = c(4,19))+
  
  geom_vline(xintercept = 1989.2,linetype="dashed")+
  geom_vline(xintercept = 2016.5,linetype="dashed")+
  annotate("text", label = "pre-treatment", x = 1988, y = 80, angle = 90,size=4, hjust = "right")+ 
  annotate("text", label = "recovery", x = 2017.5, y = 80, angle = 90,size=4, hjust = "right")+ 
  
  labs (y = expression (bold ("NO"[3]^-{}* " ("*mu*"eq L"^-1*")")),
        x = expression (bold ("WY")))+

  theme_kp()+
  theme (legend.position = "none")
```




# sulfate


```{r}

annual_sulf = ggplot (na.omit(annual), 
                      aes(x = WY, y = SO4_vol,color = Watershed,fill=Watershed,shape = Watershed,linetype=Watershed))+
  geom_point(data=all,
             aes(x = WY, y = SO4, color = "grey"))+
  geom_smooth(alpha = 0.2)+
  geom_point(size=3,stroke=1.5)+
  scale_color_got(discrete=TRUE,option = "tully")+
  scale_fill_got(discrete=TRUE,option = "tully")+
  scale_shape_manual(values = c(4,19))+
  
  geom_vline(xintercept = 1989.2,linetype="dashed")+
  geom_vline(xintercept = 2016.5,linetype="dashed")+
  annotate("text", label = "pre-treatment", x = 1988, y = 200, angle = 90,size=4, hjust = "right")+ 
  annotate("text", label = "recovery", x = 2017.5, y = 200, angle = 90,size=4, hjust = "right")+ 
  
  labs (y = expression (bold ("SO"[4]^-2* " ("*mu*"eq L"^-1*")")),
        x = expression (bold ("WY")))+
  
  theme_bw()+
  theme (legend.position = "none")+
  theme (legend.key = element_rect(size = 3))+
  theme (legend.title = element_blank())+
  theme (legend.text=element_text(size=14))+
  theme (legend.key = element_rect(size = 5),
         legend.key.size = unit(2, 'lines'))+
  theme (plot.title = element_text(hjust = 0.05,size = 14))+
  theme (axis.text=element_text(size=14,face="bold",color="black"),
         axis.title=element_text(size=14,face="bold",color="black")); annual_sulf
```



# DOC


```{r}


annual_DOC=ggplot (na.omit(annual), aes(x = WY, y = DOC_vol,color = Watershed,shape = Watershed,linetype=Watershed))+
  geom_point(data=all,
             aes(x = WY, y = DOC, color = "grey"))+
  geom_smooth(color = "grey",alpha = 0.2)+
  geom_point(size=3,stroke=1.5)+
  scale_color_got(discrete=TRUE,option = "tully")+
  scale_shape_manual(values = c(1,19))+
  
  geom_vline(xintercept = 1989.2,linetype="dashed")+
  geom_vline(xintercept = 2016.5,linetype="dashed")+
  annotate("text", label = "pre-treatment", x = 1988, y = 250, angle = 90,size=4, hjust = "right")+ 
  annotate("text", label = "recovery", x = 2017.5, y = 250, angle = 90,size=4, hjust = "right")+ 
  
  labs (y = expression (bold ("DOC ("*mu*"mol L"^-1*")")),
        x = expression (bold ("WY")))+
  
  theme_bw()+
  theme (legend.position = "none")+
  theme (legend.key = element_rect(size = 3))+
  theme (legend.title = element_blank())+
  theme (legend.text=element_text(size=14))+
  theme (legend.key = element_rect(size = 5),
         legend.key.size = unit(2, 'lines'))+
  theme (plot.title = element_text(hjust = 0.05,size = 14))+
  theme (axis.text=element_text(size=14,face="bold",color="black"),
         axis.title=element_text(size=14,face="bold",color="black"));annual_DOC
```



# ANC


```{r}



annual_anc = ggplot (na.omit(annual), 
                     aes(x = WY, y = ANC,color = Watershed,shape = Watershed,linetype=Watershed))+
   geom_smooth(color = "grey",alpha = 0.2)+
  geom_point(size=3,stroke=1.5)+
  scale_color_got(discrete=TRUE,option = "tully")+
  scale_shape_manual(values = c(1,19))+
  
  geom_vline(xintercept = 1989.2,linetype="dashed")+
  geom_vline(xintercept = 2016.5,linetype="dashed")+
  annotate("text", label = "pre-treatment", x = 1988, y = 200, angle = 90,size=4, hjust = "right")+ 
  annotate("text", label = "recovery", x = 2017.5, y = 200, angle = 90,size=4, hjust = "right")+ 
  
  labs (y = expression (bold ("ANC"),
                        x = expression (bold ("WY"))))+
  
  theme_bw()+
  theme (legend.position = "none")+
  theme (legend.key = element_rect(size = 3))+
  theme (legend.title = element_blank())+
  theme (legend.text=element_text(size=14))+
  theme (legend.key = element_rect(size = 5),
         legend.key.size = unit(2, 'lines'))+
  theme (plot.title = element_text(hjust = 0.05,size = 14))+
  theme (axis.text=element_text(size=14,face="bold",color="black"),
         axis.title=element_text(size=14,face="bold",color="black")); annual_anc
```



# pH


```{r}


annual_pH = ggplot (na.omit(annual), aes(x = WY, y = EQPH,color = Watershed,shape = Watershed,linetype=Watershed))+
  geom_smooth(color = "grey",alpha = 0.2)+
  geom_point(size=3,stroke=1.5)+
  scale_color_got(discrete=TRUE,option = "tully")+
  scale_shape_manual(values = c(1,19))+
  
  geom_vline(xintercept = 1989.2,linetype="dashed")+
  geom_vline(xintercept = 2016.5,linetype="dashed")+
  annotate("text", label = "pre-treatment", x = 1988, y = 7, angle = 90,size=4, hjust = "right")+ 
  annotate("text", label = "recovery", x = 2017.5, y = 7, angle = 90,size=4, hjust = "right")+ 
  
  labs (y = expression (bold ("Air-equilibrated pH"),
                        x = expression (bold ("WY"))))+

  theme_bw()+
  theme (legend.position = c(0.2,0.8))+
  theme (legend.key = element_rect(size = 3))+
  theme (legend.title = element_blank())+
  theme (legend.text=element_text(size=14))+
  theme (legend.key = element_rect(size = 5),
         legend.key.size = unit(2, 'lines'))+
  theme (plot.title = element_text(hjust = 0.05,size = 14))+
  theme (axis.text=element_text(size=14,face="bold",color="black"),
         axis.title=element_text(size=14,face="bold",color="black")); annual_pH


```




# summary table

```{r}
summary %>% 
  dplyr::select(species,Watershed,period,summary) %>% 
  dplyr::mutate(period = factor(period, levels = c("pre-treatment","first decade","second decade","third decade","recovery"))) %>% 
  spread(period,summary) %>% 
    knitr::kable(align = "r")
```


```{r}
all %>% 
  dplyr::filter(Year>2015) %>% 
  dplyr::mutate(date2 = as.Date(paste(Year,Month,Day, sep = "-")))->temp



ggplot(temp,aes(x = date2, y = NO3, color = Watershed,shape=Watershed))+
  geom_point(size=2,stroke=1.5)+
#  geom_path(size=1)+
 # geom_smooth(method = lm, formula = y ~ splines::bs(x, 40), se = FALSE)+
  scale_shape_manual(values = c(1,16))+
  #ylim(0,15)+
  geom_vline(xintercept = unclass(as.Date("2016-11-01")),linetype = "longdash")+
  theme_kp()+
  scale_x_date(date_breaks = "4 months", date_labels =  "%b %Y") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

ggplot(temp,aes(x = date2, y = SO4, color = Watershed,shape=Watershed))+
  geom_point(size=2,stroke=1.5)+
  geom_path(size=1)+
  scale_shape_manual(values = c(1,16))+
  ylim(0,200)+
  geom_vline(xintercept = unclass(as.Date("2016-11-01")),linetype = "longdash")+
  theme_kp()+
  scale_x_date(date_breaks = "4 months", date_labels =  "%b %Y") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

```

## fluxes

### nitrate

```{r}
annual %>% 
  dplyr::mutate(no3 = if_else(Watershed=="EB",-1*NO3,NO3),
                so4 = if_else(Watershed=="EB",-1*SO4,as.numeric(SO4)),
                no3_v = if_else(Watershed=="EB",-1*NO3_vol,NO3_vol),
                so4_v = if_else(Watershed=="EB",-1*SO4_vol,SO4_vol),)->annual2

    #  ggplot(annual2, aes(x = WY, y = no3, fill = Watershed))+
    #    geom_bar(stat = "identity")+
    #    geom_smooth(data=annual2,
    #               aes(x = WY, y = NO3_vol, color = "grey"))+
    #    scale_y_continuous(sec.axis = sec_axis(~./10, name = "Relative humidity [%]"))+
    #    scale_fill_brewer(palette = "Set2")+
    #    geom_vline(xintercept = 1989.5,linetype="dashed")+
    #    geom_vline(xintercept = 2016.5,linetype="dashed")
    #  
    #  ggplot(annual2, aes(x = WY, y = so4, fill = Watershed))+
    #    geom_bar(stat = "identity")+
    #    scale_fill_brewer(palette = "Set2")+
    #    geom_vline(xintercept = 1989.5,linetype="dashed")+
    #    geom_vline(xintercept = 2016.5,linetype="dashed")
```


```{r}
ggplot(annual2, aes(x = WY, fill = Watershed,shape=Watershed))+
  geom_bar(aes(y = no3),stat = "identity")+
  geom_line(aes(y = no3_v*10),color="black",size=0.6)+
  geom_point(aes(y = no3_v*10))+
  scale_y_continuous(sec.axis = sec_axis(~./10, name = "conc"))+
  ylab("flux")+
  #scale_fill_brewer(palette = "Dark2")+
  scale_fill_manual(values = c("#bebebe","#D95F02"))+
  geom_hline(yintercept = 0,size=0.3)+
  geom_vline(xintercept = 1989.5,linetype="dashed")+
  geom_vline(xintercept = 2016.5,linetype="dashed")+
  annotate("text", label = "pre-treatment", x = 1988, y = 650, angle = 90,size=4, hjust = "right")+ 
  annotate("text", label = "recovery", x = 2017.5, y = 650, angle = 90,size=4, hjust = "right")+ 
  theme_kp()


ggplot(annual2, aes(x = WY, fill = Watershed, shape = Watershed))+
  geom_bar(aes(y = so4),stat = "identity", alpha = 0.9)+
  geom_line(aes(y = so4_v*10),color="black",size=0.6)+
  geom_point(aes(y = so4_v*10))+
  scale_y_continuous(sec.axis = sec_axis(~./10, name = "conc"))+
  ylab("flux")+
  scale_fill_brewer(palette = "Dark2")+
  #scale_fill_manual(values = c("#6f8ea9","#003b8f"))+
  #scale_fill_manual(values = c("#d9d9d9","#D95F02"))+
  geom_vline(xintercept = 1989.5,linetype="dashed")+
  geom_vline(xintercept = 2016.5,linetype="dashed")+
  annotate("text", label = "pre-treatment", x = 1988, y = 2500, angle = 90,size=4, hjust = "right")+ 
  annotate("text", label = "recovery", x = 2017.5, y = 2500, angle = 90,size=4, hjust = "right")+ 
  theme_kp()


```

