---
title: "BBWM initial recovery"
author: "Kaizad Patel"
output: github_document
---

`r Sys.Date()`

```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo=FALSE,message=FALSE,warning=FALSE,
                      collapse = TRUE,
                      comment = "#>",
                      fig.path = "images/"
                      )

source("0-bbwm_packages.R")
source("1-bbwm_recovery_ns_Rcode.R")
make(plan)
library(harrypotter)

all = read.csv("processed/concentrations.csv")
annual = read.csv("processed/fluxes.csv")
summary = read.csv("processed/summary.csv")
deposition = read.csv("processed/deposition.csv")
combined_flux = read.csv("processed/input_output.csv")
```


## nitrate

```{r nitrate}
#nitrate
ggplot (na.omit(annual), 
                     aes(x = WY, y = NO3_vol,color = Watershed,fill=Watershed,shape = Watershed,linetype=Watershed))+
  geom_point(data=all,
             aes(x = WY, y = NO3, color = "grey"))+
  geom_smooth(alpha = 0.2)+
  geom_point(size=3,stroke=1.5)+
  scale_color_got(discrete=TRUE,option = "tully")+
  scale_fill_got(discrete=TRUE,option = "tully")+
  scale_shape_manual(values = c(4,19))+
  
  geom_vline(xintercept = 1989.2,linetype="dashed")+
  geom_vline(xintercept = 2016.5,linetype="dashed")+
  annotate("text", label = "pre-treatment", x = 1988, y = 80, angle = 90,size=4, hjust = "right")+ 
  annotate("text", label = "recovery", x = 2017.5, y = 80, angle = 90,size=4, hjust = "right")+ 
  
  labs (y = expression (bold ("NO"[3]^-{}* " ("*mu*"eq L"^-1*")")),
        x = expression (bold ("WY")))+

  theme_kp()+
  theme (legend.position = "none")
```




# sulfate


```{r}

ggplot (na.omit(annual), 
                      aes(x = WY, y = SO4_vol,color = Watershed,fill=Watershed,shape = Watershed,linetype=Watershed))+
  geom_point(data=all,
             aes(x = WY, y = SO4, color = "grey"))+
  geom_smooth(alpha = 0.2)+
  geom_point(size=3,stroke=1.5)+
  scale_color_got(discrete=TRUE,option = "tully")+
  scale_fill_got(discrete=TRUE,option = "tully")+
  scale_shape_manual(values = c(4,19))+
  
  geom_vline(xintercept = 1989.2,linetype="dashed")+
  geom_vline(xintercept = 2016.5,linetype="dashed")+
  annotate("text", label = "pre-treatment", x = 1988, y = 200, angle = 90,size=4, hjust = "right")+ 
  annotate("text", label = "recovery", x = 2017.5, y = 200, angle = 90,size=4, hjust = "right")+ 
  
  labs (y = expression (bold ("SO"[4]^-2* " ("*mu*"eq L"^-1*")")),
        x = expression (bold ("WY")))+
  
  theme_kp()+
  theme (legend.position = "none")
```



# DOC


```{r}


ggplot (na.omit(annual), aes(x = WY, y = DOC_vol,color = Watershed,shape = Watershed,linetype=Watershed))+
  geom_point(data=all,
             aes(x = WY, y = DOC, color = "grey"))+
  geom_smooth(color = "grey",alpha = 0.2)+
  geom_point(size=3,stroke=1.5)+
  scale_color_got(discrete=TRUE,option = "tully")+
  scale_shape_manual(values = c(1,19))+
  
  geom_vline(xintercept = 1989.2,linetype="dashed")+
  geom_vline(xintercept = 2016.5,linetype="dashed")+
  annotate("text", label = "pre-treatment", x = 1988, y = 250, angle = 90,size=4, hjust = "right")+ 
  annotate("text", label = "recovery", x = 2017.5, y = 250, angle = 90,size=4, hjust = "right")+ 
  
  labs (y = expression (bold ("DOC ("*mu*"mol L"^-1*")")),
        x = expression (bold ("WY")))+
  
  theme_kp()+
  theme (legend.position = "none")
```



# ANC


```{r}

ggplot (na.omit(annual), 
                     aes(x = WY, y = ANC,color = Watershed,shape = Watershed,linetype=Watershed))+
   geom_smooth(color = "grey",alpha = 0.2)+
  geom_point(size=3,stroke=1.5)+
  scale_color_got(discrete=TRUE,option = "tully")+
  scale_shape_manual(values = c(1,19))+
  
  geom_vline(xintercept = 1989.2,linetype="dashed")+
  geom_vline(xintercept = 2016.5,linetype="dashed")+
  annotate("text", label = "pre-treatment", x = 1988, y = 200, angle = 90,size=4, hjust = "right")+ 
  annotate("text", label = "recovery", x = 2017.5, y = 200, angle = 90,size=4, hjust = "right")+ 
  
  labs (y = expression (bold ("ANC"),
                        x = expression (bold ("WY"))))+
  
  theme_kp()+
  theme (legend.position = "none")
```



# pH


```{r}


ggplot (na.omit(annual), aes(x = WY, y = EQPH,color = Watershed,shape = Watershed,linetype=Watershed))+
  geom_smooth(color = "grey",alpha = 0.2)+
  geom_point(size=3,stroke=1.5)+
  scale_color_got(discrete=TRUE,option = "tully")+
  scale_shape_manual(values = c(1,19))+
  
  geom_vline(xintercept = 1989.2,linetype="dashed")+
  geom_vline(xintercept = 2016.5,linetype="dashed")+
  annotate("text", label = "pre-treatment", x = 1988, y = 7, angle = 90,size=4, hjust = "right")+ 
  annotate("text", label = "recovery", x = 2017.5, y = 7, angle = 90,size=4, hjust = "right")+ 
  
  labs (y = expression (bold ("Air-equilibrated pH"),
                        x = expression (bold ("WY"))))+

  theme_kp()+
  theme (legend.position = "none")


```




# summary table -- fluxes

```{r}
summary %>% 
  dplyr::select(species,Watershed,period,summary) %>% 
  dplyr::mutate(period = factor(period, levels = c("pre-treatment","first decade","second decade","third decade","recovery"))) %>% 
  spread(period,summary) %>% 
    knitr::kable(align = "r")

annual %>% 
  dplyr::select(Watershed,period, NO3_N, SO4_S) %>% 
  filter(!(period == "recovery" | period=="pre-treatment")) %>% 
  group_by(Watershed) %>% 
  dplyr::summarize(N = mean(NO3_N),
                S = mean(SO4_S))
```

# concentrations 

```{r concentrations}
all %>% 
  dplyr::filter(Year>2013) %>% 
  group_by(Watershed, Year, Month, Day) %>% 
  dplyr::summarise(NO3_N = mean(NO3_N, na.rm = TRUE),
                   SO4_S = mean(SO4_S, na.rm = TRUE)) %>% 
  ungroup %>% 
  dplyr::mutate(date2 = as.Date(paste(Year,Month,Day, sep = "-")))->temp



ggplot(temp,aes(x = date2, y = NO3_N, color = Watershed,shape=Watershed))+
  geom_point(size=2,stroke=1.5)+
  geom_path(linetype = "dashed", size=1)+
 # geom_smooth(method = lm, formula = y ~ splines::bs(x, 40), se = FALSE)+
  scale_color_hp(discrete=TRUE,option ="Gryffindor", direction=-1)+
  scale_shape_manual(values = c(1,16))+
  geom_vline(xintercept = unclass(as.Date("2016-11-01")),linetype = "longdash")+
  xlab("")+
  ylab("NO3-N, mg/L")+
  theme_kp()+
  scale_x_date(date_breaks = "6 months", date_labels =  "%b %Y") +
  facet_wrap(~Watershed, scales = "free")+
  #ylim(0,150)+
  #scale_y_continuous(trans='log10')
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

ggplot(temp,aes(x = date2, y = SO4_S, color = Watershed,shape=Watershed))+
  geom_point(size=2,stroke=1.5)+
  geom_path(linetype = "dashed", size=1)+
  scale_color_hp(discrete=TRUE,option ="Slytherin")+
  scale_shape_manual(values = c(1,16))+
  geom_vline(xintercept = unclass(as.Date("2016-11-01")),linetype = "longdash")+
  xlab("")+
  ylab("SO4-S, mg/L")+
  expand_limits(y=0)+
  theme_kp()+
  scale_x_date(date_breaks = "6 months", date_labels =  "%b %Y") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

```

# fluxes

### nitrate

```{r fluxes}
annual %>% 
  dplyr::mutate(no3 = if_else(Watershed=="EB",-1*NO3_N,NO3_N),
                so4 = if_else(Watershed=="EB",-1*SO4_S,as.numeric(SO4_S)),
                no3_v = if_else(Watershed=="EB",-1*NO3_vol,NO3_vol),
                so4_v = if_else(Watershed=="EB",-1*SO4_vol,SO4_vol),)->annual2

    #  ggplot(annual2, aes(x = WY, y = no3, fill = Watershed))+
    #    geom_bar(stat = "identity")+
    #    geom_smooth(data=annual2,
    #               aes(x = WY, y = NO3_vol, color = "grey"))+
    #    scale_y_continuous(sec.axis = sec_axis(~./10, name = "Relative humidity [%]"))+
    #    scale_fill_brewer(palette = "Set2")+
    #    geom_vline(xintercept = 1989.5,linetype="dashed")+
    #    geom_vline(xintercept = 2016.5,linetype="dashed")
    #  
    #  ggplot(annual2, aes(x = WY, y = so4, fill = Watershed))+
    #    geom_bar(stat = "identity")+
    #    scale_fill_brewer(palette = "Set2")+
    #    geom_vline(xintercept = 1989.5,linetype="dashed")+
    #    geom_vline(xintercept = 2016.5,linetype="dashed")
```


```{r fluxes2}
ggplot(annual2, aes(x = WY, fill = Watershed,shape=Watershed))+
  geom_bar(aes(y = no3),stat = "identity", alpha = 0.8)+
  geom_line(aes(y = no3_v*10),color="black",size=0.6)+
  geom_point(aes(y = no3_v*10), size=1.5, stroke=1)+
  scale_y_continuous(sec.axis = sec_axis(~./10, name = "conc kg/L"))+
  ylab("NO3-N flux, kg/ha/yr")+
  #scale_fill_brewer(palette = "Dark2")+
  #scale_fill_manual(values = c("#bebebe","#D95F02"))+
  scale_fill_hp(discrete=TRUE,option ="Gryffindor", direction=-1)+
  scale_shape_manual(values = c(1,19))+
  geom_hline(yintercept = 0,size=0.3)+
  geom_vline(xintercept = 1989.5,linetype="dashed")+
  geom_vline(xintercept = 2016.5,linetype="dashed")+
  annotate("text", label = "pre-treatment", x = 1988, y = 10, angle = 90,size=4, hjust = "right")+ 
  annotate("text", label = "recovery", x = 2017.5, y = 10, angle = 90,size=4, hjust = "right")+ 
  theme_kp()


ggplot(annual2, aes(x = WY, fill = Watershed, shape = Watershed))+
  geom_bar(aes(y = so4),stat = "identity", alpha = 0.9)+
  geom_line(aes(y = so4_v*10),color="black",size=0.6)+
  geom_point(aes(y = so4_v*10), size=1.5, stroke=1)+
  scale_y_continuous(sec.axis = sec_axis(~./10, name = "conc, kg/L"))+
  ylab("SO4-S flux, kg/ha/yr")+
  #scale_fill_manual(values = c("#bebebe","darkgreen"))+
  scale_fill_hp(discrete=TRUE,option ="Slytherin")+
  scale_shape_manual(values = c(1,19))+
  #scale_fill_manual(values = c("#6f8ea9","#003b8f"))+
  #scale_fill_manual(values = c("#d9d9d9","#D95F02"))+
  geom_vline(xintercept = 1989.5,linetype="dashed")+
  geom_vline(xintercept = 2016.5,linetype="dashed")+
  annotate("text", label = "pre-treatment", x = 1988, y = 40, angle = 90,size=4, hjust = "right")+ 
  annotate("text", label = "recovery", x = 2017.5, y = 40, angle = 90,size=4, hjust = "right")+ 
  theme_kp()


```


```{r fluxes3}
annual2 %>% 
  dplyr::mutate(no3_v = if_else(Watershed=="EB",no3_v*-1,no3_v),
                so4_v = if_else(Watershed=="EB",so4_v*-1,so4_v))->annual3

ggplot(annual3, aes(x = WY, fill = Watershed,shape=Watershed))+
  #geom_bar(aes(y = no3),stat = "identity", alpha = 0.8)+
  geom_line(aes(y = no3_v),color="black",size=0.6)+
  geom_point(aes(y = no3_v), size=1.5, stroke=1)+
  ylab("NO3-N conc, kg/L")+
  #scale_fill_brewer(palette = "Dark2")+
  #scale_fill_manual(values = c("#bebebe","#D95F02"))+
  scale_fill_hp(discrete=TRUE,option ="Gryffindor", direction=-1)+
  scale_shape_manual(values = c(1,19))+
  geom_hline(yintercept = 0,size=0.3)+
  geom_vline(xintercept = 1989.5,linetype="dashed")+
  geom_vline(xintercept = 2016.5,linetype="dashed")+
  annotate("text", label = "pre-treatment", x = 1988, y = 1, angle = 90,size=4, hjust = "right")+ 
  annotate("text", label = "recovery", x = 2017.5, y = 1, angle = 90,size=4, hjust = "right")+ 
  theme_kp()


ggplot(annual3, aes(x = WY, fill = Watershed, shape = Watershed))+
 # geom_bar(aes(y = so4),stat = "identity", alpha = 0.9)+
  geom_line(aes(y = so4_v),color="black",size=0.6)+
  geom_point(aes(y = so4_v), size=2, stroke=1)+
  ylab("SO4-S conc, kg/L")+
  #scale_fill_manual(values = c("#bebebe","darkgreen"))+
  scale_color_hp(discrete=TRUE,option ="Slytherin")+
  scale_shape_manual(values = c(1,19))+
  #scale_fill_manual(values = c("#6f8ea9","#003b8f"))+
  #scale_fill_manual(values = c("#d9d9d9","#D95F02"))+
  geom_vline(xintercept = 1989.5,linetype="dashed")+
  geom_vline(xintercept = 2016.5,linetype="dashed")+
  annotate("text", label = "pre-treatment", x = 1988, y = 4, angle = 90,size=4, hjust = "right")+ 
  annotate("text", label = "recovery", x = 2017.5, y = 4, angle = 90,size=4, hjust = "right")+ 
  theme_kp()


```
# deposition 

```{r, fig.asp=1, fig.dim=3}
deposition %>% 
  dplyr::mutate(S_WB = case_when(YEAR==1988~S_in,
                                 YEAR>1988&YEAR<2017~S_in+25,
                                 YEAR>2016~S_in))->deposition

ggplot(deposition, aes(x = YEAR, y = S_in))+
  geom_path()+
  geom_point(aes(shape=data_type), size=2, stroke=1)+
 # geom_path(aes(x = YEAR,y = (S_WB)),color = "red")+
  scale_shape_manual(values = c(1,19))+
  #ylim(0,7)+
  ylab(expression(bold("S, kg ha"^-1*" yr"^-1)))+
  theme_kp()

ggplot(deposition, aes(x = YEAR, y = N_in))+
  geom_path()+
  geom_point(aes(shape=data_type), size=2, stroke=1)+
  scale_shape_manual(values = c(1,19))+
#  ylim(0,7)+
  ylab(expression(bold("N, kg ha"^-1*" yr"^-1)))+
  theme_kp()
```


# retention ----

```{r}
ggplot() +
  geom_bar(data=combined_flux,aes(x = WY, y = N_cumret/20, fill = Watershed), stat = "identity", alpha = 0.3)+
  geom_point(data=combined_flux,aes(x = WY, y = N_in), stroke=1)+
  geom_path(data=combined_flux,aes(x = WY, y = N_in))+
  geom_point(data=combined_flux,aes(x = WY, y = N_out2), shape=1, stroke=1)+
  #geom_point(data=combined_flux,aes(x = WY, y = N_ret), shape=1, stroke=1, size=2)+
  geom_path(data=combined_flux,aes(x = WY, y = N_out2))+
  scale_y_continuous(sec.axis = sec_axis(~.*20, name = "cum retention, kg/ha"))+
  annotate("text", label = "input",x = 1995, y = 20)+
  annotate("text", label = "output",x = 1995, y = -10)+
  ylab("N, kg/ha/yr")+
  geom_vline(xintercept = 1989.5, linetype="dashed")+
  geom_vline(xintercept = 2016.5, linetype="dashed")+
  geom_hline(yintercept = 0)+
  scale_fill_hp(discrete=TRUE,option ="Gryffindor",direction=-1)+
  facet_wrap(~Watershed)+
  theme_kp()
  
 ggplot() +
  geom_bar(data=combined_flux,aes(fill=Watershed,x = WY, y = S_cumret/5), stat = "identity", alpha = 0.5)+
  geom_point(data=combined_flux,aes(x = WY, y = S_in), stroke=1)+
  geom_path(data=combined_flux,aes(x = WY, y = S_in))+
  geom_point(data=combined_flux,aes(x = WY, y = S_out2), shape=1, stroke=1)+
  geom_path(data=combined_flux,aes(x = WY, y = S_out2))+
  #geom_point(data=combined_flux,aes(x = WY, y = S_ret), shape=1, stroke=1, size=2)+
  scale_y_continuous(sec.axis = sec_axis(~.*5, name = "cum retention"))+
  ylab("S, kg/ha/yr")+
  geom_vline(xintercept = 1989.5, linetype="dashed")+
  geom_vline(xintercept = 2016.5, linetype="dashed")+
  geom_hline(yintercept = 0)+
  scale_fill_hp(discrete=TRUE,option ="Slytherin")+
  facet_wrap(~Watershed)+
  theme_kp()
```

